### ISSUE TITLE
Crash on v3.1.1

### ISSUE THREAD

**Issue by sternschnaube** [Crec0/map-in-slot#7]
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_9209.comp_2315()" because "mapId" is null
	at com.holebois.client_maps.client_mapsClient.getMap(client_mapsClient.java:42)
	at net.minecraft.class_1806.handler$deb000$client_maps$getMapState(class_1806.java:530)
	at net.minecraft.class_1806.method_7997(class_1806.java:56)
	at net.minecraft.class_332.handler$flg000$map-in-slot$drawMap(class_332.java:2343)
	at net.minecraft.class_332.method_51432(class_332.java:646)
	at me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition$ItemEntryRenderer.renderOverlay(ItemEntryDefinition.java:346)
	at me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition$ItemEntryRenderer.render(ItemEntryDefinition.java:287)
	at me.shedaniel.rei.impl.client.gui.widget.CachedEntryListRender.prepare(CachedEntryListRender.java:167)
	at me.shedaniel.rei.impl.client.gui.widget.CachedEntryListRender.get(CachedEntryListRender.java:115)
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.PaginatedEntryListWidget.renderEntries(PaginatedEntryListWidget.java:86)
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListWidget.method_25394(EntryListWidget.java:196)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderWidgets(ScreenOverlayImpl.java:347)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.method_25394(ScreenOverlayImpl.java:244)
	at me.shedaniel.rei.impl.client.registry.screen.ScreenRegistryImpl$5.render(ScreenRegistryImpl.java:375)
	at me.shedaniel.rei.impl.client.registry.screen.DefaultScreenOverlayRenderer.lambda$onApplied$5(DefaultScreenOverlayRenderer.java:91)
	at me.shedaniel.rei.impl.client.registry.screen.DefaultScreenOverlayRenderer.lambda$new$1(DefaultScreenOverlayRenderer.java:61)
	at net.minecraft.class_465.handler$zce000$architectury$renderBackground(class_465.java:732)
	at net.minecraft.class_465.method_25420(class_465.java:172)
	at net.minecraft.class_437.method_25394(class_437.java:129)
	at net.minecraft.class_465.method_25394(class_465.java:100)
	at net.minecraft.class_489.method_25394(class_489.java:63)
	at net.minecraft.class_437.method_47413(class_437.java:120)
	at net.minecraft.class_757.mixinextras$bridge$method_47413$213(class_757.java)
	at net.minecraft.class_757.wrapOperation$ejo000$fabric-screen-api-v1$onRenderScreen(class_757.java:3601)
	at net.minecraft.class_757.mixinextras$bridge$wrapOperation$ejo000$fabric-screen-api-v1$onRenderScreen$214(class_757.java)
	at net.minecraft.class_757.wrapOperation$gel000$optigui$renderCurrentScreenWithTooltip(class_757.java:6089)
	at net.minecraft.class_757.method_3192(class_757.java:922)
	at net.minecraft.class_310.method_1523(class_310.java:1320)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by sternschnaube** [comment]
Interesting, removing your mod fixed it for me.
Thanks 😊

**Comment by Crec0** [comment]
Well I call it. If map is not present, it returns null. Which I handle in the next line.
However, client maps mod doesn't do null check and directly calls it. Which lead to this crash.
You can try removing client maps, it will not crash either :)

**Comment by Crec0** [comment]
I have notified Kroojel, author of client maps. They will likely publish a fixed verison soon.

**Comment by sternschnaube** [comment]
Oh, I miss understood. Sounds great!

**Comment by Kroojel** [comment]
Uploaded a hotfix that should fix the issue:
https://modrinth.com/mod/client-maps/version/1.0.1+1.20.6
Let me know if that fixes it for you!
